### ISSUE TITLE
Could not locate file model.onnx

### ISSUE THREAD

**Issue by harryradford** [xenova/whisper-web#15]
During development, the `decoder_model_merged.onnx` and `encoder_model.onnx` models are fetched fine from Hugging Face or from my Express server. After building the React app with Create React App, transformers.js is trying to fetch `model.onnx` which cannot be found.

> Error: Could not locate file: "https://huggingface.co/Xenova/whisper-tiny.en/resolve/output_attentions/onnx/model.onnx".

![image](https://github.com/xenova/whisper-web/assets/27507398/ea744444-6ba6-491e-927a-593226e5f08b)

My pipeline options are `{ progress_callback, revision: "output_attentions", quantized: false }`. The task is "automatic-speech-recognition" and the model is "Xenova/whisper-tiny.en". @xenova What is `model.onnx`?

**Comment by xenova** [comment]
I believe this is because of create react app, which others have also had problems with. For more information, see https://github.com/xenova/transformers.js/issues/185

**Comment by harryradford** [comment]
Switching from CRA to Vite resolved the issue.
