### ISSUE TITLE
Error code = 6

### ISSUE THREAD

**Issue by Keith-Hon** [xenova/whisper-web#19]
<img width="524" alt="Screenshot 2023-09-02 at 3 14 33 PM" src="https://github.com/xenova/whisper-web/assets/23226987/71c943bd-e2f1-4119-83da-f46dd8fd695f">

macbook pro M2
chrome
whisper medium
chinese
transcribe

**Comment by xenova** [comment]
This error code usually represents "Out of memory". Does this happen with any of the smaller models? Or the quantized versions?

**Comment by Keith-Hon** [comment]
> This error code usually represents "Out of memory". Does this happen with any of the smaller models? Or the quantized versions?
> 
> Also, does this happen with the [hosted demo](https://hf.co/spaces/Xenova/whisper-web) too (as it looks like you're running locally)?

Ai, you are right, seems it ran out of memory on my machine. It's okay after I killed some apps. Thanks!
