### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by johanneshummel-lmi** [xenova/whisper-web#33]
Hey @xenova,
I couldn't find any license in this repo and wanted to ask wether this project can be used commercially (e.g. through MIT License).
Thanks in advance!

**Comment by xenova** [comment]
Hey! 👋 Good point, I've added the MIT license: https://github.com/xenova/whisper-web/commit/9341c394f55bc3952828db630d23faa5dec7ddc5

**Comment by johanneshummel-lmi** [comment]
Thanks a lot!
