### ISSUE TITLE
Development in firefox instruction

### ISSUE THREAD

**Issue by PushpenderSaini0** [xenova/whisper-web#8]
I was having trouble running this in dev mode in firefox.
Loading `worker.js` will fail with `SyntaxError: import declarations may only appear at top level of a module`

This is because firefox does not support worker modules by default

### Fix / Workaround
If you wish to run this in dev mode in firefox 
you will have to enable it manually via `about:config` and set `dom.workers.modules.enabled` to `true` 

> This was added in firefox111 if you have older version this may not work

**Comment by PushpenderSaini0** [comment]
Add this in `README.md` for people using firefox.
You can assign it to me, and I can raise a PR.

**Comment by xenova** [comment]
Just to clarify, you mean you are unable to run the dev server (using `npm run dev`)? I have tested the [demo app](https://huggingface.co/spaces/Xenova/whisper-web) in Firefox and it does seem to work.

Is this perhaps a known issue with vite's development mode?

**Comment by PushpenderSaini0** [comment]
Yes , you won't be able to run the app in firefox when using the command `npm run dev` but it will run fine once it's build.

No i am not  referring to "Firefox Developer Edition"

**Comment by xenova** [comment]
Okay I see, thanks for pointing that out! I just tested and you're right. 👍 Please feel free to make a PR with the note under step 2.

**Comment by max12354** [comment]
can we run whisper-large-v3-turbo
